System.config({
  paths: {
    routing: './src/routing',
    layouts: './src/layouts',
    components: './src/components',
    'components/*': './src/components/*',
    materials: './src/components/materials',
    'materials/*': './src/components/materials/*',
    form: './src/components/form',
    'form/*': './src/components/form/*',
    pages: './src/pages',
    'pages/*': './src/pages/*',
    fb: './src/rest/firebase',
    'fb/*': './src/rest/firebase/*',
    helpers: './src/rest/helpers',
    'helpers/*': './src/rest/helpers/*',
    models: './src/rest/models',
    'models/*': './src/rest/models/*',
    services: './src/rest/services',
    'services/*': './src/rest/services/*',
    stores: './src/rest/stores',
    'stores/*': './src/rest/stores/*',
    locales: './src/locales',
    'locales/*': './src/locales/*',
    images: './src/assets/images',
    'images/*': './src/assets/images/*',
    assets: './src/assets',
    'assets/*': './src/assets/*',
  }
});

